export const Users = [
    {
      id:1,
      profilePicture: "person/1.jpeg",
      username: "Alphonso Davis",
    },
    {
      id:2,
      profilePicture: "person/2.jpeg",
      username: "Cristiano Ronaldo",
    },
    {
      id:3,
      profilePicture: "person/3.jpeg",
      username: "Marcelo",
    },
    {
      id:4,
      profilePicture: "person/4.jpeg",
      username: "Wilfred Zaha",
    },
    {
      id:5,
      profilePicture: "person/5.jpeg",
      username: "Eze",
    },
    {
      id:6,
      profilePicture: "person/6.jpeg",
      username: "Dí Maria",
    },
    {
      id:7,
      profilePicture: "person/7.jpeg",
      username: "Gervonta Davis",
    },
    {
      id:8,
      profilePicture: "person/8.jpeg",
      username: "Torey Lanez",
    },
    {
      id:9,
      profilePicture: "person/9.jpeg",
      username: "Lionel Messi",
    },
    {
      id:10,
      profilePicture: "person/10.jpeg",
      username: "Tolani Animasahun",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "These pancakes were sensational.",
      photo: "post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc: "a perfectly round quarter pound.",
      photo: "post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc: "This Squid was exquisite!",
      photo: "post/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Pizza is not a 'trend' it's a way of life",
      photo: "post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "post/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "I'll kebab my way today!",
      photo: "post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];